# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    so100_arm_controller:
      type: pid_controller/PidController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

so100_arm_controller:
  ros__parameters:
    dof_names:
      - Elbow
      - Jaw
      - Pitch
      - Rotation
      - Wrist_Pitch
      - Wrist_Roll
    command_interface: position
    reference_and_state_interfaces: ["position"]
    gains:
      Elbow: {p: 1.0, i: 2.0, d: 3.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      Jaw: {p: 1.0, i: 2.0, d: 3.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      Pitch: {p: 1.0, i: 2.0, d: 3.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      Rotation: {p: 1.0, i: 2.0, d: 3.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      Wrist_Pitch: {p: 1.0, i: 2.0, d: 3.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
      Wrist_Roll: {p: 1.0, i: 2.0, d: 3.0, i_clamp_max: 5.0, i_clamp_min: -5.0}
